// <auto-generated />
namespace PrzychodniaLekarska.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2_Add_Sekretarka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_Add_Sekretarka));
        
        string IMigrationMetadata.Id
        {
            get { return "201605071523414_2_Add_Sekretarka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
