-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 21:43:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sekretarka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sekretarka` (
  `id_Sekretarka` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Sekretarka`, `mail`),
  UNIQUE INDEX `id_UNIQUE` (`id_Sekretarka` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lekarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lekarz` (
  `id_Lekarz` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `id_Sekretarka` INT NOT NULL,
  `godzinyPrzyjecOd` DATETIME NOT NULL,
  `godzinyPrzyjecDo` DATETIME NOT NULL,
  `urlop` TINYINT(1) NOT NULL,
  `urlopOd` DATETIME NULL,
  `urlopDo` DATETIME NULL,
  PRIMARY KEY (`id_Lekarz`, `mail`),
  UNIQUE INDEX `id_UNIQUE` (`id_Lekarz` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC),
  INDEX `id_Sekretarka_idx` (`id_Sekretarka` ASC),
  CONSTRAINT `id_Sekretarka`
    FOREIGN KEY (`id_Sekretarka`)
    REFERENCES `mydb`.`Sekretarka` (`id_Sekretarka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pacjent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacjent` (
  `id_Pacjent` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `pesel` INT NOT NULL,
  PRIMARY KEY (`id_Pacjent`),
  UNIQUE INDEX `id_UNIQUE` (`id_Pacjent` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecjalizacjaLekarzTyp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecjalizacjaLekarzTyp` (
  `id_SpecjalizacjaLekarzTyp` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_SpecjalizacjaLekarzTyp`),
  UNIQUE INDEX `id_SpecjalizacjaTyp_UNIQUE` (`id_SpecjalizacjaLekarzTyp` ASC),
  UNIQUE INDEX `Nazwa_UNIQUE` (`nazwa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecjalizacjaLekarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecjalizacjaLekarz` (
  `id_Lekarz` INT NOT NULL,
  `id_SpecjalizacjaLekarzTyp` INT NOT NULL,
  INDEX `id_Lekarz_idx` (`id_Lekarz` ASC),
  INDEX `id_SpecjalizacjaTyp_idx` (`id_SpecjalizacjaLekarzTyp` ASC),
  PRIMARY KEY (`id_Lekarz`),
  CONSTRAINT `id_Lekarz`
    FOREIGN KEY (`id_Lekarz`)
    REFERENCES `mydb`.`Lekarz` (`id_Lekarz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_SpecjalizacjaLekarzTyp`
    FOREIGN KEY (`id_SpecjalizacjaLekarzTyp`)
    REFERENCES `mydb`.`SpecjalizacjaLekarzTyp` (`id_SpecjalizacjaLekarzTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZabiegTyp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZabiegTyp` (
  `id_ZabiegTyp` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(100) NULL,
  PRIMARY KEY (`id_ZabiegTyp`, `nazwa`),
  UNIQUE INDEX `id_ZabiegTyp_UNIQUE` (`id_ZabiegTyp` ASC),
  UNIQUE INDEX `Nazwa_UNIQUE` (`nazwa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecjalizacjaZabieg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecjalizacjaZabieg` (
  `id_SpecjalizacjaLekarzTyp` INT NOT NULL,
  `id_ZabiegTyp` INT NOT NULL,
  INDEX `id_ZabiegTyp_idx` (`id_ZabiegTyp` ASC),
  PRIMARY KEY (`id_SpecjalizacjaLekarzTyp`),
  INDEX `index3` (`id_SpecjalizacjaLekarzTyp` ASC),
  CONSTRAINT `id_SpecjalizacjaLekarzTyp`
    FOREIGN KEY (`id_SpecjalizacjaLekarzTyp`)
    REFERENCES `mydb`.`SpecjalizacjaLekarzTyp` (`id_SpecjalizacjaLekarzTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_ZabiegTyp`
    FOREIGN KEY (`id_ZabiegTyp`)
    REFERENCES `mydb`.`ZabiegTyp` (`id_ZabiegTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zabieg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zabieg` (
  `id_Zabieg` INT NOT NULL AUTO_INCREMENT,
  `id_ZabiegTyp` INT NOT NULL,
  `id_SpecjalizacjaLekarzTyp` INT NOT NULL,
  `id_Lekarz` INT NOT NULL,
  `przedzialCzas` INT NOT NULL,
  `cena` VARCHAR(45) NOT NULL,
  `zabiegPomoc` INT NULL,
  PRIMARY KEY (`id_Zabieg`),
  INDEX `id_Lekarz_idx` (`id_Lekarz` ASC),
  UNIQUE INDEX `id_Zabieg_UNIQUE` (`id_Zabieg` ASC),
  INDEX `id_SpecjalizacjaLekarzTyp_idx` (`id_SpecjalizacjaLekarzTyp` ASC),
  CONSTRAINT `id_ZabiegTyp`
    FOREIGN KEY (`id_ZabiegTyp`)
    REFERENCES `mydb`.`ZabiegTyp` (`id_ZabiegTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Lekarz`
    FOREIGN KEY (`id_Lekarz`)
    REFERENCES `mydb`.`Lekarz` (`id_Lekarz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_SpecjalizacjaLekarzTyp`
    FOREIGN KEY (`id_SpecjalizacjaLekarzTyp`)
    REFERENCES `mydb`.`SpecjalizacjaLekarzTyp` (`id_SpecjalizacjaLekarzTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wizyta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wizyta` (
  `id_Wizyta` INT NOT NULL AUTO_INCREMENT,
  `id_Zabieg` INT NOT NULL,
  `id_Pacjent` INT NOT NULL,
  `WizytaDateOd` DATETIME NOT NULL,
  `WizytaDateDo` DATETIME NULL,
  `id_LekarzZastepczy` INT NULL,
  `opinia` TEXT(500) NULL,
  `akceptacja` TINYINT(1) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id_Wizyta`),
  UNIQUE INDEX `id_wizyta_UNIQUE` (`id_Wizyta` ASC),
  INDEX `id_Zabieg_idx` (`id_Zabieg` ASC),
  INDEX `id_Pacjent_idx` (`id_Pacjent` ASC),
  INDEX `id_LekarzZastepczy_idx` (`id_LekarzZastepczy` ASC),
  CONSTRAINT `id_Zabieg`
    FOREIGN KEY (`id_Zabieg`)
    REFERENCES `mydb`.`Zabieg` (`id_Zabieg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Pacjent`
    FOREIGN KEY (`id_Pacjent`)
    REFERENCES `mydb`.`Pacjent` (`id_Pacjent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_LekarzZastepczy`
    FOREIGN KEY (`id_LekarzZastepczy`)
    REFERENCES `mydb`.`Lekarz` (`id_Lekarz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PomocMedyczna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PomocMedyczna` (
  `id_PomocMedyczna` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_PomocMedyczna`, `mail`),
  UNIQUE INDEX `id_UNIQUE` (`id_PomocMedyczna` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecjalizacjaPomocMedycznaTyp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecjalizacjaPomocMedycznaTyp` (
  `id_SpecjalizacjaPomocMedycznaTyp` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_SpecjalizacjaPomocMedycznaTyp`),
  UNIQUE INDEX `id_SpecjalizacjaTyp_UNIQUE` (`id_SpecjalizacjaPomocMedycznaTyp` ASC),
  UNIQUE INDEX `Nazwa_UNIQUE` (`nazwa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecjalizacjaPomocMedyczna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecjalizacjaPomocMedyczna` (
  `id_PomocMedyczna` INT NOT NULL,
  `id_SpecjalizacjaPomocMedycznaTyp` INT NOT NULL,
  PRIMARY KEY (`id_PomocMedyczna`),
  INDEX `id_PomoczMedyczna_idx` (`id_PomocMedyczna` ASC),
  INDEX `id_SpecjalizacjaPomocMedycznaTyp_idx` (`id_SpecjalizacjaPomocMedycznaTyp` ASC),
  CONSTRAINT `id_PomoczMedyczna`
    FOREIGN KEY (`id_PomocMedyczna`)
    REFERENCES `mydb`.`PomocMedyczna` (`id_PomocMedyczna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_SpecjalizacjaPomocMedycznaTyp`
    FOREIGN KEY (`id_SpecjalizacjaPomocMedycznaTyp`)
    REFERENCES `mydb`.`SpecjalizacjaPomocMedycznaTyp` (`id_SpecjalizacjaPomocMedycznaTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WizytaPomocMedyczna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WizytaPomocMedyczna` (
  `id_Wizyta` INT NOT NULL,
  `id_PomocMedyczna` INT NOT NULL,
  PRIMARY KEY (`id_Wizyta`),
  INDEX `id_PomocMedyczna_idx` (`id_PomocMedyczna` ASC),
  CONSTRAINT `id_Wizyta`
    FOREIGN KEY (`id_Wizyta`)
    REFERENCES `mydb`.`Wizyta` (`id_Wizyta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_PomocMedyczna`
    FOREIGN KEY (`id_PomocMedyczna`)
    REFERENCES `mydb`.`PomocMedyczna` (`id_PomocMedyczna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RelacjaSpecjalizacjiLekPomMed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RelacjaSpecjalizacjiLekPomMed` (
  `id_SpecjalizacjaLekarzTyp` INT NOT NULL,
  `id_SpecjalizacjaPomocMedycznaTyp` INT NOT NULL,
  PRIMARY KEY (`id_SpecjalizacjaLekarzTyp`),
  INDEX `id_SpecjalizacjaPomocMedycznaTyp_idx` (`id_SpecjalizacjaPomocMedycznaTyp` ASC),
  CONSTRAINT `id_SpecjalizacjaLekarzTyp`
    FOREIGN KEY (`id_SpecjalizacjaLekarzTyp`)
    REFERENCES `mydb`.`SpecjalizacjaLekarzTyp` (`id_SpecjalizacjaLekarzTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_SpecjalizacjaPomocMedycznaTyp`
    FOREIGN KEY (`id_SpecjalizacjaPomocMedycznaTyp`)
    REFERENCES `mydb`.`SpecjalizacjaPomocMedycznaTyp` (`id_SpecjalizacjaPomocMedycznaTyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id_Lekarz` INT, `mail` INT, `haslo` INT, `imie` INT, `nazwisko` INT, `telefon` INT, `adres` INT, `id_Sekretarka` INT, `godzinyPrzyjecOd` INT, `godzinyPrzyjecDo` INT, `urlop` INT, `urlopOd` INT, `urlopDo` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;
CREATE  OR REPLACE VIEW `view1` AS SELECT * FROM Lekarz;
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
